var warehouseApp = angular.module('warehouseApp', []);

warehouseApp.controller('warehouseCtrl', function($scope){
	$scope.stores = [
	{'img': '',
	'location':"Borlänge",
	'value': '1'},
	{'img': '',
	'location':"Göteborg Kållered",
	'value': '2'},
	{'img': '',
	'location':"Haparanda Tornio",
	'value': '3'},
	{'img': '',
	'location':"Jönköping",
	'value': '4'},
	{'img': '',
	'location':"Malmö",
	'value': '5'},
	{'img': '',
	'location':"Stockholm Kungens kurva",
	'value': '6'},
	{'img': '',
	'location':"Älmhult",
	'value': '7'},
	{'img': '',
	'location':"Gävle",
	'value': '8'},
	{'img': '',
	'location':"Göteborg Bäckebol",
	'value': '9'},
	{'img': '',
	'location':"Helsingborg",
	'value': '10'},
	{'img': '',
	'location':"Kalmar",
	'value': '11'},
	{'img': '',
	'location':"Linköping",
	'value': '12'},
	{'img': '',
	'location':"Stockholm Barkarby",
	'value': '13'},
	{'img': '',
	'location':"Sundsvall",
	'value': '14'},
	{'img': '',
	'location':"Uddevalla",
	'value': '15'},
	{'img': '',
	'location':"Västerås",
	'value':'16'},
	];
});