var warehouseApp = angular.module('warehouseApp', []);

warehouseApp.controller('warehouseCtrl', function($scope){
	$scope.stores = [
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Borlänge",
	'value':1},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Göteborg Kållered",
	'value':2},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Haparanda Tornio",
	'value':3},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Jönköping",
	'value':4},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Malmö",
	'value':5},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Stockholm Kungens kurva",
	'value':6},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Älmhult",
	'value':7},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Gävle",
	'value':8},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Göteborg Bäckebol",
	'value':9},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Helsingborg",
	'value':10},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Kalmar",
	'value':11},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Linköping",
	'value':12},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Stockholm Barkarby",
	'value':13},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Sundsvall",
	'value':14},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Uddevalla",
	'value':15},
	{'img': 'http://www.bwpgroup.com/wp-content/uploads/2013/07/Ikea.jpg',
	'location':"Västerås",
	'value':16},
	];
});